version: '3'
services:
  zakupator_frontend:
    image: node
    container_name: zakupator_frontend
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www